function fulltable = construct_table(spike_data)
%% construct table from spike_data structure
fulltable=table();
for i=1:length(spike_data)
    % table with spiking data for each neuron and trial
    all_neurons_table = table();
    n_neurons = length(spike_data(i).neuronData);
    for j = 1:n_neurons
        neuron_data = spike_data(i).neuronData(j);
        trial_num = length(neuron_data.trialNumber);
        neuron_table = table(...
            repmat(neuron_data.Neuron, trial_num, 1), ...
            repmat(neuron_data.brainArea, trial_num, 1), ...
            repmat(neuron_data.NeuronCount, trial_num, 1), ...
            neuron_data.trialNumber,...
            repmat(neuron_data.clusterID, trial_num, 1), ...
            neuron_data.stimuliSpikeCounts, ...
            neuron_data.meanStimuliSpikeCounts, ...
            'VariableNames', {'Neuron', 'brainArea', 'NeuronCount', ...
            'trialNumber', 'clusterId', 'stimuliSpikeCounts', 'meanStimuliSpikeCount'});
        all_neurons_table = [all_neurons_table; neuron_table];
    end
    
    % table with stimuli info for each trial
    stimuli_table = table(...
        spike_data(i).stimuliLearn,...
        spike_data(i).stimuliLearnCat,...
        spike_data(i).stimuliLearnCatNum,...
        spike_data(i).LearnCorrect,...
        spike_data(i).LearnRT,...
        spike_data(i).RecogResponse,...
        spike_data(i).RecogRT,...
        'VariableNames', {'stimuliLearn', 'stimuliLearnCat', 'stimuliLearnCatNum', ...
        'learnCorrect', 'learnRT', 'RecogResponse', 'RecogRT'});
    stimuli_table = repmat(stimuli_table, n_neurons, 1);
    
    % table with meta data
    n_rows = size(all_neurons_table,1);
    meta_table = table(...
        spike_data(i).participant,...
        spike_data(i).session,...
        spike_data(i).taskvariant,...
        spike_data(i).numtrials,...
        spike_data(i).diagnosisCode,...
        spike_data(i).age,...
        spike_data(i).LearnImageDur,...
        'VariableNames', {'Participant', 'Session', 'TaskVariant', ...
        'NumTrials', 'DiagnosisCode', 'Age', 'learnImageDur'});
    meta_table = repmat(meta_table, n_rows, 1);  
    
    % append everything
    fulltable=[fulltable; [meta_table, stimuli_table, all_neurons_table]];
end
end
