function rank_table = b_convert2ranks(pe_hpc_pls, pe_amyg_pls, spikenum_hpc_pls, ...
    behav_dat, neuron_nums, trial_nums, spike_summary)
%%b_convert2ranks Converting neuron and behavioral into rank space. 

rel_inds.hpc = find(pe_hpc_pls.lvlv_corrs.all_layers{1}~=0);
rel_inds.amyg = find(pe_hpc_pls.lvlv_corrs.all_layers{1}~=0 & pe_amyg_pls.lvlv_corrs.late_layers{1}~=0);

rank_table.hpc = table( ...
    tiedrank(pe_hpc_pls.lvlv_corrs.early_layers{1}(rel_inds.hpc))',...
    tiedrank(pe_hpc_pls.lvlv_corrs.late_layers{1}(rel_inds.hpc))',...
    tiedrank(pe_hpc_pls.lvlv_corrs.all_layers{1}(rel_inds.hpc))',...
    tiedrank(spikenum_hpc_pls.lvlv_corrs.late_layers{1}(rel_inds.hpc))',...    % late_layers
    tiedrank(pe_amyg_pls.lvlv_corrs.late_layers{1}(rel_inds.hpc))',...
    tiedrank(pe_amyg_pls.lvlv_corrs.early_layers{1}(rel_inds.hpc))',...
    tiedrank(behav_dat.session_1.rlogP(rel_inds.hpc)),...
    tiedrank(behav_dat.session_1.rcwP(rel_inds.hpc)),...
    tiedrank(behav_dat.session_1.dprim(rel_inds.hpc)),...
    tiedrank(behav_dat.session_1.rConf(rel_inds.hpc)),...
    tiedrank(behav_dat.session_1.crit(rel_inds.hpc)),...
    tiedrank(neuron_nums(rel_inds.hpc,1)),...
    tiedrank(trial_nums(rel_inds.hpc,1)),...
    (behav_dat.session_1.Age(rel_inds.hpc)),...
    (behav_dat.session_1.ID(rel_inds.hpc)),...
    categorical(spike_summary.task_vars(rel_inds.hpc,1)),...
    categorical(spike_summary.image_dur(rel_inds.hpc,1)),...
    tiedrank(spike_summary.avg_pe(rel_inds.hpc,1)),...
    tiedrank(spike_summary.spike_rate(rel_inds.hpc,1)),...
    (behav_dat.session_1.learn_accuracy(rel_inds.hpc)),...
    'VariableNames', ... 
    {'PE_early','PE_late','PE_all','SpikeNum_late','Amyg_PE_late',...
    'Amyg_PE_early','rlogP', 'rcwP', 'dprim', 'rconf',...
    'crit','numNeurons', 'numTrials','Age', 'ID','TaskVersion', ... 
    'ImageDuration', 'AvgPE', 'SpikeRate', 'learnAccuracy'});

rank_table.amyg = table( ...
    tiedrank(pe_hpc_pls.lvlv_corrs.early_layers{1}(rel_inds.amyg))',...
    tiedrank(pe_hpc_pls.lvlv_corrs.late_layers{1}(rel_inds.amyg))',...
    tiedrank(pe_hpc_pls.lvlv_corrs.all_layers{1}(rel_inds.amyg))',...
    tiedrank(spikenum_hpc_pls.lvlv_corrs.late_layers{1}(rel_inds.amyg))',...    % late_layers
    tiedrank(pe_amyg_pls.lvlv_corrs.late_layers{1}(rel_inds.amyg))',...
    tiedrank(pe_amyg_pls.lvlv_corrs.early_layers{1}(rel_inds.amyg))',...
    tiedrank(behav_dat.session_1.rlogP(rel_inds.amyg)),...
    tiedrank(behav_dat.session_1.rcwP(rel_inds.amyg)),...
    tiedrank(behav_dat.session_1.dprim(rel_inds.amyg)),...
    tiedrank(behav_dat.session_1.rConf(rel_inds.amyg)),...
    tiedrank(behav_dat.session_1.crit(rel_inds.amyg)),...
    tiedrank(neuron_nums(rel_inds.amyg,1)),...
    tiedrank(trial_nums(rel_inds.amyg,1)),...
    (behav_dat.session_1.Age(rel_inds.amyg)),...
    (behav_dat.session_1.ID(rel_inds.amyg)),...
    categorical(spike_summary.task_vars(rel_inds.amyg,1)),...
    categorical(spike_summary.image_dur(rel_inds.amyg,1)),...
    tiedrank(spike_summary.avg_pe(rel_inds.amyg,1)),...
    tiedrank(spike_summary.spike_rate(rel_inds.amyg,1)),...
    (behav_dat.session_1.learn_accuracy(rel_inds.amyg)),...
    'VariableNames', ... 
    {'PE_early','PE_late','PE_all','SpikeNum_late','Amyg_PE_late',...
    'Amyg_PE_early','rlogP', 'rcwP', 'dprim', 'rconf',...
    'crit','numNeurons', 'numTrials','Age', 'ID', 'TaskVersion', ... 
    'ImageDuration', 'AvgPE', 'SpikeRate', 'learnAccuracy'});

end