function [result_early, result_late, result_all] = perm_run_pls_models(neuro_data, stim_data, n_trials_used)
% run PLS models for early, late and all VGG/HMAX layers
    % set up some more options for PLS
    option = [];
    option.method = 3; % behavioural PLS
    option.num_perm = 1; 
    option.num_boot = 1;
    option.cormode = 8; % rank correlation

    % set up the stimulus info matrix for 
    % a model that includes all vgg and HMAX layers
    option.stacked_behavdata = [ ...
        stim_data.c1_sum,...                                           % hmax sum
        stim_data.c2_sum,...
        stim_data.c1_sd,...                                            % hmax sd
        stim_data.c2_sd,...
        stim_data.first_layer_sum,...                                  % vgg sum
        stim_data.second_layer_sum,...
        stim_data.third_layer_sum,...
        stim_data.fourth_layer_sum,...
        stim_data.fifth_layer_sum,...
        stim_data.first_layer_nz_sd,...                                % vgg sd
        stim_data.second_layer_nz_sd,...
        stim_data.third_layer_nz_sd,...
        stim_data.fourth_layer_nz_sd,...
        stim_data.fifth_layer_nz_sd,...
        stim_data.first_layer_nz_num,...                               % vgg num
        stim_data.second_layer_nz_num,...
        stim_data.third_layer_nz_num,...
        stim_data.fourth_layer_nz_num,...
        stim_data.fifth_layer_nz_num];

    % run model
    % neural matrix consists of neuron and trial-wise PE for motif lengths 2, 3, & 4
    result_all = pls_analysis({neuro_data}, n_trials_used, 1, option);

    % run one model using late layers
    option.stacked_behavdata = [ ...
        stim_data.c2_sum,...
        stim_data.c2_sd,...
        stim_data.third_layer_sum,...
        stim_data.fourth_layer_sum,...
        stim_data.fifth_layer_sum,...
        stim_data.third_layer_nz_sd,...
        stim_data.fourth_layer_nz_sd,...
        stim_data.fifth_layer_nz_sd,...
        stim_data.third_layer_nz_num,...
        stim_data.fourth_layer_nz_num,...
        stim_data.fifth_layer_nz_num];
    result_late = pls_analysis({neuro_data}, n_trials_used, 1, option);

    % run one model using early layers
    option.stacked_behavdata = [ ...
        stim_data.c1_sum,...                                           % hmax sum
        stim_data.c1_sd,...                                            % hmax sd   
        stim_data.first_layer_sum,...                                  % vgg sum
        stim_data.second_layer_sum,...
        stim_data.third_layer_sum,...
        stim_data.first_layer_nz_sd,...                                % vgg sd
        stim_data.second_layer_nz_sd,...
        stim_data.third_layer_nz_sd,...
        stim_data.first_layer_nz_num,...                               % vgg num
        stim_data.second_layer_nz_num,...
        stim_data.third_layer_nz_num];
                                       
    result_early = pls_analysis({neuro_data}, n_trials_used, 1, option);
end