function plot_stim_weights(stim_weights, plot_ids)
    %% Plot layer-specific weights
    for sub_id = 1:size(stim_weights,1)
        if ~isempty(stim_weights{sub_id,1})
            all_abs_stim_weights(:,sub_id) = (abs(stim_weights{sub_id,1}(:,1)));
        else
            all_abs_stim_weights(:,sub_id) = NaN(size(stim_weights{1,1},1),1);
        end
    end

    for lay = 1:size(stim_weights{1},1)
        abs_stim_weights{lay,1} = (all_abs_stim_weights(lay,plot_ids))';
    end

    xdat = repmat([1,2,4:6,8:10, 12:14], length(plot_ids),1)+...
        zscore(rand(length(plot_ids),size(stim_weights{1},1)))*.01;

    n_cols = [135, 35, 49;...
        135, 35, 49;...
        [255, 200, 87;...
        233, 114, 76;...
        197, 40, 61];...
        [255, 200, 87;...
        233, 114, 76;...
        197, 40, 61];...
        [255, 200, 87;...
        233, 114, 76;...
        197, 40, 61]]/255;


    figure
    hold on
    for lay = 1:size(stim_weights{1},1)
        scatter(xdat(:,lay), abs_stim_weights{lay},120,'filled',...
            'MarkerfaceColor', n_cols(lay,:), 'MarkerFaceAlpha',...
            .7)
        % plot the mean
        scatter(mean(xdat(:,lay)), mean(abs_stim_weights{lay}),...
            350,'filled',...
            'MarkerfaceColor', n_cols(lay,:))

        % also plot individual connecting lines
        for i_pat = 1:size(xdat,1)
            if lay<size(stim_weights{1},1)
                if ~ismember(lay,[2,5,8])
                    plot([xdat(i_pat,lay), xdat(i_pat,lay+1)],...
                        [abs_stim_weights{lay}(i_pat) abs_stim_weights{lay+1}(i_pat)],...
                        'Color', [.6 .6 .6])
                end
            end
        end

        % connect the mean
        if lay<size(stim_weights{1},1)
            if ~ismember(lay,[2,5,8])
                plot([mean(xdat(:,lay)), mean(xdat(:,lay+1))],...
                    [mean(abs_stim_weights{lay}) mean(abs_stim_weights{lay+1})],...
                    'Color', [0 0 0], 'LineWidth', 5)
            end
        end
    end
    ylim([-.1 .7])
    xlim([-1 16])
    xticks([1,2,4:6,8:10, 12:14])
    xticklabels({'C2 SD', 'C2 Sum',...
        'VGG3 sum', 'VGG4 sum', 'VGG5 sum',...
        'VGG3 SD', 'VGG4 SD', 'VGG5 SD',...
        'VGG3 nz', 'VGG4 nz', 'VGG5 nz'})

end